### ISSUE TITLE
didn't work at 1.20.1

### ISSUE THREAD

**Issue by mezer0** [Lortseam/better-mount-hud#10]
![image](https://github.com/Lortseam/better-mount-hud/assets/61835081/be7e634c-19da-444d-87f5-ca5788644d84)
![image](https://github.com/Lortseam/better-mount-hud/assets/61835081/3d77fd17-45b8-4b76-9e1c-16d9dd1acc26)
not even appear in the mods setting, also in hotkey settings

**Comment by Lortseam** [comment]
What exactly doesn't work?

**Comment by mezer0** [comment]
hud

**Comment by mezer0** [comment]
xD
