### ISSUE TITLE
Fix the weird jump bar offset

### ISSUE THREAD

**Issue by nco2k** [Lortseam/better-mount-hud#11]
the jump bar has a weird offset on the y-axis. i know this is a minecraft thing, but it would be cool if you could fix it, and make the mount hud even better.

this is how it currently looks like:
![pic_a](https://github.com/Lortseam/better-mount-hud/assets/26080123/7e86d1cf-c571-44f0-a577-d54bbd2fd923)

this is how i wish it would look like:
![pic_b](https://github.com/Lortseam/better-mount-hud/assets/26080123/ba71682c-9e67-4320-b909-80f54a173bc4)

**Comment by Lortseam** [comment]
This seems to be fixed in Minecraft 1.20.6.
