### ISSUE TITLE
Air bubles are blocked by horse health

### ISSUE THREAD

**Issue by SkyLLerGithub** [Lortseam/better-mount-hud#21]
When riding a horse underwater (For example a skeleton horse) the air bubble which indicate the amount of air the player have before they start drowning is blocked by the health of the entity that the player is currently riding.

Video of the bug:

https://github.com/user-attachments/assets/ce9c68af-d15f-4892-bf7c-bd5006155bee

**Comment by Lortseam** [comment]
Should be fixed in the latest version.

**Comment by bravely-beep** [comment]
Any chance of backporting this fix to 1.21.1?
