### ISSUE TITLE
Better Mount HUD crashes on 1.19.3

### ISSUE THREAD

**Issue by Kichura** [Lortseam/better-mount-hud#4]
When starting up the [latest version](https://www.curseforge.com/minecraft/mc-mods/better-mount-hud/files/4147405) of Better Mount HUD to 1.19.3, The client will instantly [crash](https://pastebin.com/raw/Q72Trsz7).

**Comment by Lortseam** [comment]
I can't reproduce the crash. What other mods do you have installed?

**Comment by Kichura** [comment]
Seems to be caused by horse stats vanilla.
