### ISSUE TITLE
Mount hearts not showing up properly.

### ISSUE THREAD

**Issue by iambeingtracked** [Lortseam/better-mount-hud#5]
Here's how it looks with the vanilla resource pack: https://0x0.st/oCi-.png
Here's how it looks with a simple vanillatweaks build: https://0x0.st/oCio.png

No idea what could be causing this

**Comment by Lortseam** [comment]
Sorry for the late response, do you still experience this issue?

**Comment by iambeingtracked** [comment]
Haven't played Minecraft in a while but it seems to work now
